name: Ejecutar pruebas Karate API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-karate-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Ejecutar pruebas Karate
        run: mvn clean test -Dkarate.outputHtmlReport=true

      - name: Comprimir reporte Karate
        run: |
          if [ -d "target/karate-reports" ]; then
            zip -r KarateReports.zip target/karate-reports
          else
            echo "No se encontró el directorio target/karate-reports. Saltando compresión."
          fi

      - name: Subir reporte como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: KarateReports
          path: KarateReports.zip